### PR TITLE
Added cmake build script

### PR DESCRIPTION
**Pull request by Acclution**
I have tested this on linux, windows (visual studio) and android and it works. So I thought I'd create a pull request for it if you want it =)

### CODE REVIEW

**Comment by BastiaanOlij** [comment]
@Acclution can you check if this still works now that we switched to nativescript 1.1? also can you squash your commits into a single commit please?

**Comment by BastiaanOlij** [comment]
@karroffel , what is your opinion on this. It's nice to have alternative build systems but without someone actively maintaining a scons alternative it will just cause confusion?

**Comment by karroffel** [comment]
I think the same, it seems like a nice addition, but unless it'd be maintained (and checked by CI - so the maintainer would have to be there to help update it) it seems like it would cause more confusion than good.

**Comment by Acclution** [comment]
No need to merge it if it will cause confusion. Made it because I wanted to make android builds and the scons alternative seems to not have that. I have never worked with scons so it was easier for me to get android going with cmake.
Checking compatibility with nativescript 1.1 now. I might need to add an include directory when I look at the changes to SConstruct.

**Comment by BastiaanOlij** [comment]
@Acclution I still haven't got android to work with scons, just using ndk_build atm :)

I think it'll be a worthy addition if you can make sure it works with the latest changes and if you're willing to keep it up to date. That's my only concern, if it's not maintained it'll lead to issues down the line

**Comment by Acclution** [comment]
Hmm.. Maintaining it should not be a problem I think because I am using it myself. The only problem might be testing because I only have one android phone though I could perhaps test on emulators?

I have now converted my project to nativescript 1.1 and it works fine on linux though I have linker problems on android build. After I have fixed that I will test and push a new version of the cmake script.

**Comment by BastiaanOlij** [comment]
@Acclution sounds good, as you're testing both on Linux and Android I think that proves enough the build script is at least complete and if you'll keep using it regularly we'll find any breaking changes quickly enough. When others use it for the other platforms they may mention switches that need to chance but thats fine.

Any particular reason you didn't use scons for Android? Or just more comfortable with cmake? I'm finally getting into Android for GearVR/Go and using ndk-build for now but just because I'm completely unfamiliar with the platform.

**Comment by Acclution** [comment]
More comfortable with cmake and I get automagic QtCreator integration which is nice =)
Though I might not need godot-cpp to be cmake. I only need a way to build and get the libraries for android so I can link to them.. can you do that with ndk-build?

**Comment by BastiaanOlij** [comment]
No something went wrong, as you can see with all the commits that were added, though I do think you're on the right track.

Something you could try and do is to check out master, make sure you pull it from upstream, create a new branch and then cherry pick your commit with:
```
git cherry-pick b342d889234db9f8ecb11b369b33afeb67ab6f61
```

If that works delete/rename your old branch, rename your new branch to your old branch and do a forced push.

**Comment by Acclution** [comment]
now it look nicer =)

**Comment by BastiaanOlij** [comment]
Let's merge it in and see where it takes us :)

**Pull request merged**
