### PR TITLE
Do not include Ref.hpp file in Reference.hpp

### PR DESCRIPTION
**Pull request by RameshRavone**

### CODE REVIEW

**Comment by karroffel** [comment]
cc @Zylann

**Comment by Zylann** [comment]
Is it preventing compilation? It works on my end

**Comment by RameshRavone** [comment]
Yes, including `Ref.hpp` results in compilation error,

**Comment by RameshRavone** [comment]
Ref needs Reference, so including `Ref.hpp` before defining Reference means type conversion will fail in `Ref.hpp` results compiling error,

**Comment by Zylann** [comment]
Hmm actually you're right... Godot reference.h doesn't include Ref, it is defined below, so it's like only Ref.hpp includes Reference.h in the end. It's ok then

**Pull request merged**
