### PR TITLE
Vector3: add missing methods

### PR DESCRIPTION
**Pull request by lupoDharkael**
See https://github.com/GodotNativeTools/godot-cpp/issues/189

### CODE REVIEW

**Comment by BastiaanOlij** [comment]
@karroffel I'm happy to merge this, my only question is, should we be using std::abs ?

**Comment by karroffel** [comment]
I think the rest of the files uses the c math stuff, so no `std`, but I could be wrong here

**Comment by BastiaanOlij** [comment]
Ok, when I have a free hour I'll double check it, maybe just alter it to using standard math stuff.

**Comment by BastiaanOlij** [comment]
Dang, this went into nativescript 1-1 :) I'll redo it manually :)

**Pull request merged**
