### PR TITLE
Add a type conversion to Variant for anything that supports ___get_from_variant()

### PR DESCRIPTION
**Pull request by Windfisch**

### CODE REVIEW

**Comment by Windfisch** [comment]
There has been some discussion in #269's discussion page about whether the `static_cast` is safe, and whether it should be a `reinterpret_cast` semantically; one might read that discussion before merging.

**Comment by karroffel** [comment]
So technically this would mean that if you attempt to cast to `float4` from some SIMD library it would attempt it but fail in the instanciation step. If my C++ knowledge is good enough this should not be a problem because SFINAE and stuff. Somebody correct me if I'm wrong.

**Comment by BastiaanOlij** [comment]
That goes way over my head, would be good if some people test this. I'm happy to merge it and then revert it if shit hits the fan?

**Comment by karroffel** [comment]
Sounds good to me! That's what master branches are for :smile:

**Pull request merged**
