### PR TITLE
Cpp editor plugins

### PR DESCRIPTION
**Pull request by Redwan13**
https://github.com/GodotNativeTools/godot-cpp/issues/110

### CODE REVIEW

**Comment by karroffel** [comment]
Thanks! I see it's still using `std::string`, you said you wanted to replace those, right?

**Comment by Redwan13** [comment]
I tried to replace `std::string` in template params but library starts to crash on load. Looks like dereferencing a null pointer while trying to access
```
const godot::String NodeClass##LibraryPath(GdnsPath);
const godot::String NodeClass##HierarchyParent(#NodeHierarchyParent);
```
Looks like init issue. didn't figure out it yet.

**Comment by BastiaanOlij** [comment]
@Redwan13 could you rebase this pull request? Got broken with going to Nativescript 1.1 I think.

**Comment by karroffel** [comment]
Seeing this again, I'm fine with the changes as they seem to be completely opt-in and you don't pay anything if you don't use them.

But maybe the naming could be different? `NodeWrapper` doesn't say as much as, say, `EditorPluginNodeWrapper`

**Comment by BastiaanOlij** [comment]
I suggest we leave this until redwan has time to rebase and polish up. :)

**Comment by Redwan13** [comment]
I have completely forgotten about this pull request:) 

I'll rebase it, but I think on Nativescript 1.1 it will be much simpler to build editor nodes.

**Comment by BastiaanOlij** [comment]
@Redwan13 indeed it is more straight forward so I do not know how valid this still is. For my procmesh library I ended up writing the editor plugin side in GDScript only doing heavy lifting stuff in GDNative.

**Pull request closed without merging**
